services:
  backend:
    build:
      context: ./server
    container_name: food-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
    container_name: food-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend